CREATE TABLE `projects` (`id` text PRIMARY KEY NOT NULL,`seller_email` text NOT NULL,`title` text NOT NULL,`slug` text NOT NULL UNIQUE,`category` text NOT NULL,`short_description` text NOT NULL,`problem_statement` text,`abstract` text,`description` text,`features_json` text NOT NULL DEFAULT '[]',`tech_stack_json` text NOT NULL DEFAULT '[]',`difficulty` text,`requested_price_paise` integer NOT NULL DEFAULT 0,`proposed_price_paise` integer,`final_price_paise` integer,`files_json` text NOT NULL DEFAULT '[]',`thumbnail_key` text,`demo_url` text,`status` text NOT NULL DEFAULT 'DRAFT',`verified` integer NOT NULL DEFAULT 0,`ownership_confirmed` integer NOT NULL DEFAULT 0,`admin_notes` text,`seller_message` text,`published_at` text,`created_at` text NOT NULL,`updated_at` text NOT NULL);
CREATE INDEX `idx_projects_status_published` ON `projects` (`status`,`published_at`);
CREATE INDEX `idx_projects_seller_updated` ON `projects` (`seller_email`,`updated_at`);
CREATE TABLE `project_build_requests` (`id` text PRIMARY KEY NOT NULL,`user_email` text NOT NULL,`name` text NOT NULL,`mobile` text,`whatsapp` text,`title` text NOT NULL,`category` text NOT NULL,`problem_statement` text NOT NULL,`requirements` text NOT NULL,`features_json` text NOT NULL DEFAULT '[]',`preferred_technology` text,`references_json` text NOT NULL DEFAULT '[]',`requested_deadline` text,`quoted_price_paise` integer,`estimated_delivery` text,`status` text NOT NULL DEFAULT 'REQUEST_SUBMITTED',`admin_notes` text,`user_message` text,`created_at` text NOT NULL,`updated_at` text NOT NULL);
CREATE INDEX `idx_build_requests_user_updated` ON `project_build_requests` (`user_email`,`updated_at`);
CREATE INDEX `idx_build_requests_status_updated` ON `project_build_requests` (`status`,`updated_at`);
CREATE TABLE `project_audit_log` (`id` text PRIMARY KEY NOT NULL,`project_id` text,`build_request_id` text,`actor_email` text NOT NULL,`action` text NOT NULL,`details_json` text NOT NULL DEFAULT '{}',`created_at` text NOT NULL);
CREATE TABLE `project_orders` (`id` text PRIMARY KEY NOT NULL,`project_id` text NOT NULL,`buyer_email` text NOT NULL,`amount_paise` integer NOT NULL,`payment_status` text NOT NULL DEFAULT 'PENDING',`razorpay_order_id` text UNIQUE,`razorpay_payment_id` text,`created_at` text NOT NULL,`paid_at` text);
CREATE INDEX `idx_project_orders_buyer_project` ON `project_orders` (`buyer_email`,`project_id`,`payment_status`);
