import { NextResponse } from "next/server";
import { database } from "../../db";
import { getViewer } from "../../../supabase/server";
const admin=async()=>{const v=await getViewer();return v?.isAdmin&&["OWNER","OPERATIONS"].includes(v.adminRole??"")?v:null};
const projectStatuses=new Set(["DRAFT","PENDING_REVIEW","UNDER_REVIEW","CHANGES_REQUESTED","REJECTED","PRICE_PROPOSED","READY_TO_PUBLISH","PUBLISHED","UNPUBLISHED","ARCHIVED"]);
const hasDocs=(raw:string)=>{try{const kinds=new Set(JSON.parse(raw||"[]").map((x:any)=>x.kind));return kinds.has("ZIP")&&kinds.has("REPORT")}catch{return false}};
export async function GET(){if(!await admin())return NextResponse.json({error:"Admin access required"},{status:403});const db=database();const [projects,stats,sales,buildRequests]=await Promise.all([db.prepare("SELECT id,title,seller_email,seller_name,seller_mobile,seller_whatsapp,seller_upi_id,category,requested_price_paise,final_price_paise,status,verified,files_json,seller_payout_status,sold_at,created_at,updated_at FROM projects WHERE status NOT IN ('UNPUBLISHED','ARCHIVED') ORDER BY updated_at DESC LIMIT 200").all(),db.prepare("SELECT status,COUNT(*) count FROM projects WHERE status NOT IN ('UNPUBLISHED','ARCHIVED') GROUP BY status").all(),db.prepare("SELECT o.id,o.project_id,o.buyer_email,o.amount_paise,o.gateway_fee_paise,o.payment_status,o.payout_status,o.paid_at,p.title,p.seller_name,p.seller_email,p.seller_upi_id FROM project_orders o JOIN projects p ON p.id=o.project_id WHERE o.payment_status='PAID' ORDER BY o.paid_at DESC LIMIT 200").all(),db.prepare("SELECT id,name,mobile,whatsapp,user_email,title,category,problem_statement,requirements,preferred_technology,requested_deadline,status,quoted_price_paise,estimated_delivery,user_message,admin_notes,created_at,updated_at FROM project_build_requests WHERE status!='REJECTED' ORDER BY updated_at DESC LIMIT 200").all()]);return NextResponse.json({projects:projects.results,stats:stats.results,sales:sales.results,buildRequests:buildRequests.results})}
export async function POST(request:Request){const viewer=await admin();if(!viewer)return NextResponse.json({error:"Admin access required"},{status:403});const body=await request.json() as any,db=database(),now=new Date().toISOString();
if(body.kind==="project"){const id=String(body.id??""),status=String(body.status??""),price=body.finalPrice===undefined?null:Number(body.finalPrice);if(!projectStatuses.has(status)||(price!==null&&(!Number.isFinite(price)||price<0)))return NextResponse.json({error:"Invalid project update"},{status:400});const current=await db.prepare("SELECT files_json,seller_name,seller_mobile,seller_whatsapp,seller_upi_id FROM projects WHERE id=?").bind(id).first<any>();if(!current)return NextResponse.json({error:"Project not found"},{status:404});if(status==="PUBLISHED"&&(price===null||!hasDocs(current.files_json)||!current.seller_name||!current.seller_mobile||!current.seller_whatsapp||!current.seller_upi_id))return NextResponse.json({error:"Set price and upload ZIP and Report before publishing"},{status:400});await db.prepare("UPDATE projects SET status=?,final_price_paise=CASE WHEN ? IS NULL THEN final_price_paise ELSE ? END,updated_at=? WHERE id=?").bind(status,price,price===null?null:Math.round(price*100),now,id).run();return NextResponse.json({ok:true})}
if(body.kind==="build"){const id=String(body.id??""),status=String(body.status??""),allowed=new Set(["REQUEST_SUBMITTED","UNDER_REVIEW","ACCEPTED","QUOTE_SENT","DEVELOPMENT_STARTED","IN_DEVELOPMENT","TESTING","DOCUMENTATION","READY","DELIVERED","REJECTED","CANCELLED"]),quote=body.quotedPrice===undefined?null:Number(body.quotedPrice);if(!allowed.has(status)||(quote!==null&&(!Number.isFinite(quote)||quote<0)))return NextResponse.json({error:"Invalid build request update"},{status:400});const result=await db.prepare("UPDATE project_build_requests SET status=?,quoted_price_paise=CASE WHEN ? IS NULL THEN quoted_price_paise ELSE ? END,estimated_delivery=?,admin_notes=?,user_message=?,updated_at=? WHERE id=?").bind(status,quote,quote===null?null:Math.round(quote*100),String(body.estimatedDelivery??"").slice(0,120),String(body.notes??"").slice(0,4000),String(body.message??"").slice(0,1000),now,id).run();return result.meta.changes?NextResponse.json({ok:true}):NextResponse.json({error:"Build request not found"},{status:404})}
if(body.kind==="payout"){const id=String(body.orderId??""),status=String(body.payoutStatus??"");if(!["PENDING","PROCESSING","PAID"].includes(status))return NextResponse.json({error:"Invalid payout"},{status:400});const sale=await db.prepare("SELECT project_id FROM project_orders WHERE id=? AND payment_status='PAID'").bind(id).first<any>();if(!sale)return NextResponse.json({error:"Sale not found"},{status:404});await db.batch([db.prepare("UPDATE project_orders SET payout_status=? WHERE id=?").bind(status,id),db.prepare("UPDATE projects SET seller_payout_status=?,seller_payout_paid_at=CASE WHEN ?='PAID' THEN ? ELSE seller_payout_paid_at END WHERE id=?").bind(status,status,now,sale.project_id)]);return NextResponse.json({ok:true})}
return NextResponse.json({error:"Invalid action"},{status:400})}
