import { NextResponse } from "next/server";
import { database } from "../../db";
import { getViewer } from "../../../supabase/server";

const admin=async()=>{const viewer=await getViewer();return viewer?.isAdmin&&["OWNER","OPERATIONS"].includes(viewer.adminRole??"")?viewer:null};
const statuses=new Set(["DRAFT","PENDING_REVIEW","UNDER_REVIEW","CHANGES_REQUESTED","REJECTED","PRICE_PROPOSED","READY_TO_PUBLISH","PUBLISHED","UNPUBLISHED","ARCHIVED"]);
const requiredDocuments=(raw:string)=>{try{const kinds=new Set(JSON.parse(raw||"[]").map((file:any)=>file.kind));return ["ZIP","REPORT"].every(kind=>kinds.has(kind));}catch{return false}};

export async function GET(){if(!await admin())return NextResponse.json({error:"Admin access required"},{status:403});const db=database();const [projects,stats,sales]=await Promise.all([db.prepare("SELECT id,title,seller_email,seller_name,seller_mobile,seller_whatsapp,seller_upi_id,category,requested_price_paise,final_price_paise,status,verified,files_json,seller_payout_status,sold_at,created_at,updated_at FROM projects WHERE status NOT IN ('UNPUBLISHED','ARCHIVED') ORDER BY updated_at DESC LIMIT 200").all(),db.prepare("SELECT status,COUNT(*) count FROM projects WHERE status NOT IN ('UNPUBLISHED','ARCHIVED') GROUP BY status").all(),db.prepare("SELECT o.id,o.project_id,o.buyer_email,o.amount_paise,o.gateway_fee_paise,o.payment_status,o.payout_status,o.paid_at,p.title,p.seller_name,p.seller_email,p.seller_upi_id FROM project_orders o JOIN projects p ON p.id=o.project_id WHERE o.payment_status='PAID' ORDER BY o.paid_at DESC LIMIT 200").all()]);return NextResponse.json({projects:projects.results,stats:stats.results,sales:sales.results})}

export async function POST(request:Request){const viewer=await admin();if(!viewer)return NextResponse.json({error:"Admin access required"},{status:403});const body=await request.json() as any,db=database(),now=new Date().toISOString();
 if(body.kind==="create-project"){const title=String(body.title??"").trim(),category=String(body.category??"").trim(),description=String(body.description??"").trim(),price=Number(body.price),sellerName=String(body.sellerName??"").trim(),sellerEmail=String(body.sellerEmail??"").trim(),sellerMobile=String(body.sellerMobile??"").replace(/\D/g,""),sellerWhatsapp=String(body.sellerWhatsapp??"").replace(/\D/g,""),sellerUpi=String(body.sellerUpi??"").trim();if(title.length<3||!category||description.length<20||!Number.isFinite(price)||price<0||sellerName.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(sellerEmail)||sellerMobile.length<10||sellerWhatsapp.length<10||sellerUpi.length<3)return NextResponse.json({error:"Complete project, seller contact and UPI payout details"},{status:400});const id=crypto.randomUUID(),slug=`${title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${id.slice(0,6)}`;await db.prepare("INSERT INTO projects (id,seller_email,seller_name,seller_mobile,seller_whatsapp,seller_upi_id,title,slug,category,short_description,description,features_json,tech_stack_json,requested_price_paise,final_price_paise,files_json,status,verified,ownership_confirmed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,sellerEmail,sellerName,sellerMobile,sellerWhatsapp,sellerUpi,title,slug,category,description,description,"[]","[]",Math.round(price*100),Math.round(price*100),"[]","DRAFT",1,1,now,now).run();return NextResponse.json({ok:true,id})}
 if(body.kind==="project"){const id=String(body.id??""),status=String(body.status??"");if(!statuses.has(status))return NextResponse.json({error:"Invalid project status"},{status:400});const current=await db.prepare("SELECT status,files_json,seller_name,seller_mobile,seller_whatsapp,seller_upi_id FROM projects WHERE id=?").bind(id).first<any>();if(!current)return NextResponse.json({error:"Project not found"},{status:404});const finalPrice=body.finalPrice===undefined?null:Number(body.finalPrice);if(finalPrice!==null&&(!Number.isFinite(finalPrice)||finalPrice<0||finalPrice>1_000_000))return NextResponse.json({error:"Invalid final price"},{status:400});if(status==="PUBLISHED"&&(finalPrice===null||!requiredDocuments(current.files_json)||!current.seller_name||!current.seller_mobile||!current.seller_whatsapp||!current.seller_upi_id))return NextResponse.json({error:"Set the final price and upload ZIP, Report and IEEE documents before publishing"},{status:400});await db.batch([db.prepare("UPDATE projects SET status=?,final_price_paise=CASE WHEN ? IS NULL THEN final_price_paise ELSE ? END,verified=CASE WHEN ? THEN 1 ELSE verified END,published_at=CASE WHEN ?='PUBLISHED' THEN ? ELSE published_at END,updated_at=? WHERE id=?").bind(status,finalPrice,finalPrice===null?null:Math.round(finalPrice*100),Boolean(body.verified),status,now,now,id),db.prepare("INSERT INTO project_audit_log (id,project_id,actor_email,action,created_at) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),id,viewer.email,`ADMIN_${status}`,now)]);return NextResponse.json({ok:true})}
 if(body.kind==="payout"){const orderId=String(body.orderId??""),payoutStatus=String(body.payoutStatus??"");if(!["PENDING","PROCESSING","PAID"].includes(payoutStatus))return NextResponse.json({error:"Invalid payout status"},{status:400});const sale=await db.prepare("SELECT project_id FROM project_orders WHERE id=? AND payment_status='PAID'").bind(orderId).first<any>();if(!sale)return NextResponse.json({error:"Sold project not found"},{status:404});await db.batch([db.prepare("UPDATE project_orders SET payout_status=? WHERE id=?").bind(payoutStatus,orderId),db.prepare("UPDATE projects SET seller_payout_status=?,seller_payout_paid_at=CASE WHEN ?='PAID' THEN ? ELSE seller_payout_paid_at END,updated_at=? WHERE id=?").bind(payoutStatus,payoutStatus,now,now,sale.project_id)]);return NextResponse.json({ok:true})}
 return NextResponse.json({error:"Invalid action"},{status:400})
}
